support github actions for the asio-juce branch
Andersama/obs-asio pull request #120
Opened 2022-09-05 08:58 UTC by wkpark

This is based on the recent obs-ndi work
 * `.github/*` files are imported from the obs-ndi
 * fetch the JUCE and the asio-sdk sources on the fly.
 * misc fixes added to make it work with the Actions flows
 * support OBS 28 now

you can download this obs-asio prebuilt from the following link:
https://github.com/wkpark/obs-asio/actions/runs/2991805352

2022-09-07 23:20 UTC, WizardCM requested changes

2022-09-07 23:20 UTC, WizardCM commented on .github/workflows/main.yml
> +      - master
Please exclude the `master` branch here.

```suggestion
```

2022-09-07 23:20 UTC, WizardCM commented on .github/workflows/main.yml
> +      - master
Please exclude the `master` branch here.

```suggestion
```

2022-09-08 01:11 UTC, Andersama commented
Hey just a heads up, Wizard and I are likely to get around to this over the weekend, but there needs to be a couple changes. For licensing problems with the steinberg sdk you'll want to try to automate the build against: https://github.com/Andersama/JUCE/tree/open_asio_juce

Shouldn't require the steinberg sdk, also if possible squash all your commits into one (if not we'll likely end up doing that anyway).

2022-09-08 17:22 UTC, wkpark commented
> Hey just a heads up, Wizard and I are likely to get around to this over the weekend, but there needs to be a couple changes. For licensing problems with the steinberg sdk you'll want to try to automate the build against: https://github.com/Andersama/JUCE/tree/open_asio_juce
> 

OK. now the `openasio_sdk` support fix has been cherry-picked manually and applied.

> Shouldn't require the steinberg sdk, also if possible squash all your commits into one (if not we'll likely end up doing that anyway).

and many fixes have been rebased to show this PR briefly (might be rebased again after all hunks are reviewed carefully, as you wish.)

2022-09-08 17:25 UTC, Andersama commented
Ah I forgot I had to modify Juce furthur, @wkpark the kAsioCanReport value we never found, we only found a reference to the name*. Do you have a source for where that value came from that isn't from the steinberg sdk? I think that would bring the openasio wrapper into full compatiblity with the asio standard because I think that was the only thing missing.

Second, does the FetchContent_Declare cmake thing not work for building a branch of juce directly? I'd rather just do that over having bash / shell scripting to move things around.

2022-09-08 18:09 UTC, wkpark commented
> Ah I forgot I had to modify Juce furthur, @wkpark the kAsioCanReportOverload value we never found, we only found a reference to the name*. Do you have a source for where that value came from that isn't from the steinberg sdk? I think that would bring the openasio wrapper into full compatibility with the asio standard because I think that was the only thing missing. It also might be the the source for some people's issue with crackling / popping.
> 
I've found `kAsioCanReportOverload` at
https://fossies.org/dox/lmms_1.2.2/asio_8h.html#adc29c2ff13d900c2f185ee95427fb06caecc90f364253d8c306dc720c9604d6c0
(and it seems this const added a recent version of the SDK.)

> Second, does the FetchContent_Declare cmake thing not work for building a branch of juce directly? I'd rather just do that over having bash / shell scripting to move things around.

you mean the `prepare.sh`?
undefined `kAsioCanReportOverload` prevent me to build with https://github.com/Andersama/JUCE/tree/open_asio_juce

I've just seen your last fix so I'll fix/rebase it soon again.

2022-09-08 18:28 UTC, Andersama commented
Unfortunately that link won't work as a source, it's a doxygen doc of the steinberg sdk. Funny I played around with carla for a while because it was a pretty ok asio host, although it had some issues. Originally, 5 or so years ago pkv and I spent about 3+ days trying to reverse engineer the asio header for just this reason. Pretty confident that was the only thing missing because I vaguely remember making the same edit to build Juce.

In short, good luck finding a source for that value that isn't the steinberg sdk.

2022-09-08 19:11 UTC, wkpark commented
> 
> I've just seen your last fix so I'll fix/rebase it soon again.

This is the last build. https://github.com/wkpark/obs-asio/actions/runs/3017510916#artifacts

2022-09-08 19:25 UTC, Andersama commented
Unless I'm mistaken you don't need the `ENABLE_OPENASIO_SDK` option, that's sort've what I was aiming for.

2022-09-10 22:42 UTC, Andersama commented
@wkpark sorry, I ended up force-pushing to your branch instead of mine (I'll try to restore it later), if you'd like make sure you create a new workflows branch as a backup*.

2022-09-11 07:21 UTC, wkpark commented
no problem.
Thanks for your concern! :)

This PR closed by commit https://github.com/Andersama/obs-asio/commit/cef5c6115fbe38280dcf1da5db6f4da533ecf117

2022-09-11 11:14 UTC, closed without merging